//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CodingLei_Model.TableModel
{
    /// <summary>
    /// 实体类Community_Topic。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Community_Topic")]
    [Serializable]
    public partial class Community_Topic : Entity
    {
        #region Model
        private int _Id;
        private int? _DelStatus;
        private DateTime? _AddTime;
        private string _Contents;
        private string _imgs;
        private string _openid;
        private int? _IsRead;
        private string _Name;
        private string _HeadImg;
        private string _CardId;
        private int? _IsClosed;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DelStatus")]
        public int? DelStatus
        {
            get { return _DelStatus; }
            set
            {
                this.OnPropertyValueChange("DelStatus");
                this._DelStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AddTime")]
        public DateTime? AddTime
        {
            get { return _AddTime; }
            set
            {
                this.OnPropertyValueChange("AddTime");
                this._AddTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Contents")]
        public string Contents
        {
            get { return _Contents; }
            set
            {
                this.OnPropertyValueChange("Contents");
                this._Contents = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("imgs")]
        public string imgs
        {
            get { return _imgs; }
            set
            {
                this.OnPropertyValueChange("imgs");
                this._imgs = value;
            }
        }
        /// <summary>
        /// 患者openid
        /// </summary>
        [Field("openid")]
        public string openid
        {
            get { return _openid; }
            set
            {
                this.OnPropertyValueChange("openid");
                this._openid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IsRead")]
        public int? IsRead
        {
            get { return _IsRead; }
            set
            {
                this.OnPropertyValueChange("IsRead");
                this._IsRead = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("HeadImg")]
        public string HeadImg
        {
            get { return _HeadImg; }
            set
            {
                this.OnPropertyValueChange("HeadImg");
                this._HeadImg = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CardId")]
        public string CardId
        {
            get { return _CardId; }
            set
            {
                this.OnPropertyValueChange("CardId");
                this._CardId = value;
            }
        }
        /// <summary>
        /// 是否关闭（0,no  1 yes）
        /// </summary>
        [Field("IsClosed")]
        public int? IsClosed
        {
            get { return _IsClosed; }
            set
            {
                this.OnPropertyValueChange("IsClosed");
                this._IsClosed = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.DelStatus,
                _.AddTime,
                _.Contents,
                _.imgs,
                _.openid,
                _.IsRead,
                _.Name,
                _.HeadImg,
                _.CardId,
                _.IsClosed,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._DelStatus,
                this._AddTime,
                this._Contents,
                this._imgs,
                this._openid,
                this._IsRead,
                this._Name,
                this._HeadImg,
                this._CardId,
                this._IsClosed,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Community_Topic");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DelStatus = new Field("DelStatus", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Contents = new Field("Contents", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field imgs = new Field("imgs", "Community_Topic", "");
            /// <summary>
			/// 患者openid
			/// </summary>
			public readonly static Field openid = new Field("openid", "Community_Topic", "患者openid");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsRead = new Field("IsRead", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field HeadImg = new Field("HeadImg", "Community_Topic", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CardId = new Field("CardId", "Community_Topic", "");
            /// <summary>
			/// 是否关闭（0,no  1 yes）
			/// </summary>
			public readonly static Field IsClosed = new Field("IsClosed", "Community_Topic", "是否关闭（0,no  1 yes）");
        }
        #endregion
        
        public int Number { get; set; }
    }
}