//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CodingLei_Model.TableModel
{
    /// <summary>
    /// 实体类dt_order。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("dt_order")]
    [Serializable]
    public partial class dt_order : Entity
    {
        #region Model
        private int _id;
        private string _title;
        private string _number;
        private string _img_url;
        private string _name;
        private string _telephone;
        private string _address;
        private string _details;
        private string _username;
        private int? _priority;
        private int? _state;
        private string _add_time;
        private string _update_time;
        private string _update_name;
        private string _type;
        private string _group_id;
        private string _mark;
        private string _solveImg;
        private string _AppointUser;

        /// <summary>
        /// 
        /// </summary>
        [Field("id")]
        public int id
        {
            get { return _id; }
            set
            {
                this.OnPropertyValueChange("id");
                this._id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("title")]
        public string title
        {
            get { return _title; }
            set
            {
                this.OnPropertyValueChange("title");
                this._title = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("number")]
        public string number
        {
            get { return _number; }
            set
            {
                this.OnPropertyValueChange("number");
                this._number = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("img_url")]
        public string img_url
        {
            get { return _img_url; }
            set
            {
                this.OnPropertyValueChange("img_url");
                this._img_url = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("name")]
        public string name
        {
            get { return _name; }
            set
            {
                this.OnPropertyValueChange("name");
                this._name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("telephone")]
        public string telephone
        {
            get { return _telephone; }
            set
            {
                this.OnPropertyValueChange("telephone");
                this._telephone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("address")]
        public string address
        {
            get { return _address; }
            set
            {
                this.OnPropertyValueChange("address");
                this._address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("details")]
        public string details
        {
            get { return _details; }
            set
            {
                this.OnPropertyValueChange("details");
                this._details = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("username")]
        public string username
        {
            get { return _username; }
            set
            {
                this.OnPropertyValueChange("username");
                this._username = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("priority")]
        public int? priority
        {
            get { return _priority; }
            set
            {
                this.OnPropertyValueChange("priority");
                this._priority = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("state")]
        public int? state
        {
            get { return _state; }
            set
            {
                this.OnPropertyValueChange("state");
                this._state = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("add_time")]
        public string add_time
        {
            get { return _add_time; }
            set
            {
                this.OnPropertyValueChange("add_time");
                this._add_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("update_time")]
        public string update_time
        {
            get { return _update_time; }
            set
            {
                this.OnPropertyValueChange("update_time");
                this._update_time = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("update_name")]
        public string update_name
        {
            get { return _update_name; }
            set
            {
                this.OnPropertyValueChange("update_name");
                this._update_name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("type")]
        public string type
        {
            get { return _type; }
            set
            {
                this.OnPropertyValueChange("type");
                this._type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("group_id")]
        public string group_id
        {
            get { return _group_id; }
            set
            {
                this.OnPropertyValueChange("group_id");
                this._group_id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("mark")]
        public string mark
        {
            get { return _mark; }
            set
            {
                this.OnPropertyValueChange("mark");
                this._mark = value;
            }
        }
        /// <summary>
        /// 解决完成图片
        /// </summary>
        [Field("solveImg")]
        public string solveImg
        {
            get { return _solveImg; }
            set
            {
                this.OnPropertyValueChange("solveImg");
                this._solveImg = value;
            }
        }
        /// <summary>
        /// 指定处理人
        /// </summary>
        [Field("AppointUser")]
        public string AppointUser
        {
            get { return _AppointUser; }
            set
            {
                this.OnPropertyValueChange("AppointUser");
                this._AppointUser = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.id,
                _.title,
                _.number,
                _.img_url,
                _.name,
                _.telephone,
                _.address,
                _.details,
                _.username,
                _.priority,
                _.state,
                _.add_time,
                _.update_time,
                _.update_name,
                _.type,
                _.group_id,
                _.mark,
                _.solveImg,
                _.AppointUser,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._id,
                this._title,
                this._number,
                this._img_url,
                this._name,
                this._telephone,
                this._address,
                this._details,
                this._username,
                this._priority,
                this._state,
                this._add_time,
                this._update_time,
                this._update_name,
                this._type,
                this._group_id,
                this._mark,
                this._solveImg,
                this._AppointUser,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "dt_order");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field title = new Field("title", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field number = new Field("number", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field img_url = new Field("img_url", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field name = new Field("name", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field telephone = new Field("telephone", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field address = new Field("address", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field details = new Field("details", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field username = new Field("username", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field priority = new Field("priority", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field state = new Field("state", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field add_time = new Field("add_time", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_time = new Field("update_time", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field update_name = new Field("update_name", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field type = new Field("type", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field group_id = new Field("group_id", "dt_order", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field mark = new Field("mark", "dt_order", "");
            /// <summary>
			/// 解决完成图片
			/// </summary>
			public readonly static Field solveImg = new Field("solveImg", "dt_order", "解决完成图片");
            /// <summary>
			/// 指定处理人
			/// </summary>
			public readonly static Field AppointUser = new Field("AppointUser", "dt_order", "指定处理人");
        }
        #endregion
    }
}