//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CodingLei_Model.TableModel
{
    /// <summary>
    /// 实体类Duty。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Duty")]
    [Serializable]
    public partial class Duty : Entity
    {
        #region Model
        private int _Id;
        private string _Name;
        private string _Openid;
        private string _WeekDay;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Name")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Openid")]
        public string Openid
        {
            get { return _Openid; }
            set
            {
                this.OnPropertyValueChange("Openid");
                this._Openid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("WeekDay")]
        public string WeekDay
        {
            get { return _WeekDay; }
            set
            {
                this.OnPropertyValueChange("WeekDay");
                this._WeekDay = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.Name,
                _.Openid,
                _.WeekDay,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._Name,
                this._Openid,
                this._WeekDay,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Duty");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Duty", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Name = new Field("Name", "Duty", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Openid = new Field("Openid", "Duty", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WeekDay = new Field("WeekDay", "Duty", "");
        }
        #endregion
    }
}