//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CodingLei_Model.TableModel
{
    /// <summary>
    /// 实体类Users。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Users")]
    [Serializable]
    public partial class Users : Entity
    {
        #region Model
        private int _Id;
        private string _UserId;
        private string _UserId2;
        private int _UserNo;
        private string _UserName;
        private string _Password;
        private string _IDNumber;
        private int _PrivId;
        private string _Expand;
        private string _PostPriv;
        private string _PostDept;
        private int _DeptId;
        private bool _CanBroadcast;
        private bool _Sex;
        private DateTime _Birthday;
        private bool _IsHideBirthday;
        private string _TelNoDept;
        private string _FaxNoDept;
        private string _AddressHome;
        private string _ZipHome;
        private string _TelHome;
        private string _Mobile;
        private bool _IsHideMobile;
        private string _Bp;
        private string _Email;
        private string _Oicq;
        private string _Icq;
        private string _Msn;
        private string _Skype;
        private byte[] _Photo;
        private string _NickName;
        private int _Avatar;
        private bool _MenuType;
        private bool _MenuHide;
        private bool _SmsOn;
        private int _CallSound;
        private int _Theme;
        private string _Note;
        private string _MytableLeft;
        private string _MytableRight;
        private int _EmailCapacity;
        private int _FolderCapacity;
        private decimal _OnlineTime;
        private int? _DutyType;
        private string _AttendCard;
        private int _State;
        private int _State2;
        private DateTime _LastPassTime;
        private DateTime _LastVisitTime;
        private string _LastIp;
        private bool _Disabled;
        private string _BindIp;
        private bool _UsingKey;
        private string _UGuid;
        private string _UKey;
        private string _UExt;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserId")]
        public string UserId
        {
            get { return _UserId; }
            set
            {
                this.OnPropertyValueChange("UserId");
                this._UserId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserId2")]
        public string UserId2
        {
            get { return _UserId2; }
            set
            {
                this.OnPropertyValueChange("UserId2");
                this._UserId2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserNo")]
        public int UserNo
        {
            get { return _UserNo; }
            set
            {
                this.OnPropertyValueChange("UserNo");
                this._UserNo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UserName")]
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this.OnPropertyValueChange("UserName");
                this._UserName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Password")]
        public string Password
        {
            get { return _Password; }
            set
            {
                this.OnPropertyValueChange("Password");
                this._Password = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IDNumber")]
        public string IDNumber
        {
            get { return _IDNumber; }
            set
            {
                this.OnPropertyValueChange("IDNumber");
                this._IDNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PrivId")]
        public int PrivId
        {
            get { return _PrivId; }
            set
            {
                this.OnPropertyValueChange("PrivId");
                this._PrivId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Expand")]
        public string Expand
        {
            get { return _Expand; }
            set
            {
                this.OnPropertyValueChange("Expand");
                this._Expand = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PostPriv")]
        public string PostPriv
        {
            get { return _PostPriv; }
            set
            {
                this.OnPropertyValueChange("PostPriv");
                this._PostPriv = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("PostDept")]
        public string PostDept
        {
            get { return _PostDept; }
            set
            {
                this.OnPropertyValueChange("PostDept");
                this._PostDept = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DeptId")]
        public int DeptId
        {
            get { return _DeptId; }
            set
            {
                this.OnPropertyValueChange("DeptId");
                this._DeptId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CanBroadcast")]
        public bool CanBroadcast
        {
            get { return _CanBroadcast; }
            set
            {
                this.OnPropertyValueChange("CanBroadcast");
                this._CanBroadcast = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Sex")]
        public bool Sex
        {
            get { return _Sex; }
            set
            {
                this.OnPropertyValueChange("Sex");
                this._Sex = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Birthday")]
        public DateTime Birthday
        {
            get { return _Birthday; }
            set
            {
                this.OnPropertyValueChange("Birthday");
                this._Birthday = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IsHideBirthday")]
        public bool IsHideBirthday
        {
            get { return _IsHideBirthday; }
            set
            {
                this.OnPropertyValueChange("IsHideBirthday");
                this._IsHideBirthday = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TelNoDept")]
        public string TelNoDept
        {
            get { return _TelNoDept; }
            set
            {
                this.OnPropertyValueChange("TelNoDept");
                this._TelNoDept = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FaxNoDept")]
        public string FaxNoDept
        {
            get { return _FaxNoDept; }
            set
            {
                this.OnPropertyValueChange("FaxNoDept");
                this._FaxNoDept = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AddressHome")]
        public string AddressHome
        {
            get { return _AddressHome; }
            set
            {
                this.OnPropertyValueChange("AddressHome");
                this._AddressHome = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("ZipHome")]
        public string ZipHome
        {
            get { return _ZipHome; }
            set
            {
                this.OnPropertyValueChange("ZipHome");
                this._ZipHome = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("TelHome")]
        public string TelHome
        {
            get { return _TelHome; }
            set
            {
                this.OnPropertyValueChange("TelHome");
                this._TelHome = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Mobile")]
        public string Mobile
        {
            get { return _Mobile; }
            set
            {
                this.OnPropertyValueChange("Mobile");
                this._Mobile = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("IsHideMobile")]
        public bool IsHideMobile
        {
            get { return _IsHideMobile; }
            set
            {
                this.OnPropertyValueChange("IsHideMobile");
                this._IsHideMobile = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Bp")]
        public string Bp
        {
            get { return _Bp; }
            set
            {
                this.OnPropertyValueChange("Bp");
                this._Bp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Email")]
        public string Email
        {
            get { return _Email; }
            set
            {
                this.OnPropertyValueChange("Email");
                this._Email = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Oicq")]
        public string Oicq
        {
            get { return _Oicq; }
            set
            {
                this.OnPropertyValueChange("Oicq");
                this._Oicq = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Icq")]
        public string Icq
        {
            get { return _Icq; }
            set
            {
                this.OnPropertyValueChange("Icq");
                this._Icq = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Msn")]
        public string Msn
        {
            get { return _Msn; }
            set
            {
                this.OnPropertyValueChange("Msn");
                this._Msn = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Skype")]
        public string Skype
        {
            get { return _Skype; }
            set
            {
                this.OnPropertyValueChange("Skype");
                this._Skype = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Photo")]
        public byte[] Photo
        {
            get { return _Photo; }
            set
            {
                this.OnPropertyValueChange("Photo");
                this._Photo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("NickName")]
        public string NickName
        {
            get { return _NickName; }
            set
            {
                this.OnPropertyValueChange("NickName");
                this._NickName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Avatar")]
        public int Avatar
        {
            get { return _Avatar; }
            set
            {
                this.OnPropertyValueChange("Avatar");
                this._Avatar = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MenuType")]
        public bool MenuType
        {
            get { return _MenuType; }
            set
            {
                this.OnPropertyValueChange("MenuType");
                this._MenuType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MenuHide")]
        public bool MenuHide
        {
            get { return _MenuHide; }
            set
            {
                this.OnPropertyValueChange("MenuHide");
                this._MenuHide = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("SmsOn")]
        public bool SmsOn
        {
            get { return _SmsOn; }
            set
            {
                this.OnPropertyValueChange("SmsOn");
                this._SmsOn = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("CallSound")]
        public int CallSound
        {
            get { return _CallSound; }
            set
            {
                this.OnPropertyValueChange("CallSound");
                this._CallSound = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Theme")]
        public int Theme
        {
            get { return _Theme; }
            set
            {
                this.OnPropertyValueChange("Theme");
                this._Theme = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Note")]
        public string Note
        {
            get { return _Note; }
            set
            {
                this.OnPropertyValueChange("Note");
                this._Note = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MytableLeft")]
        public string MytableLeft
        {
            get { return _MytableLeft; }
            set
            {
                this.OnPropertyValueChange("MytableLeft");
                this._MytableLeft = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("MytableRight")]
        public string MytableRight
        {
            get { return _MytableRight; }
            set
            {
                this.OnPropertyValueChange("MytableRight");
                this._MytableRight = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("EmailCapacity")]
        public int EmailCapacity
        {
            get { return _EmailCapacity; }
            set
            {
                this.OnPropertyValueChange("EmailCapacity");
                this._EmailCapacity = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("FolderCapacity")]
        public int FolderCapacity
        {
            get { return _FolderCapacity; }
            set
            {
                this.OnPropertyValueChange("FolderCapacity");
                this._FolderCapacity = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("OnlineTime")]
        public decimal OnlineTime
        {
            get { return _OnlineTime; }
            set
            {
                this.OnPropertyValueChange("OnlineTime");
                this._OnlineTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DutyType")]
        public int? DutyType
        {
            get { return _DutyType; }
            set
            {
                this.OnPropertyValueChange("DutyType");
                this._DutyType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AttendCard")]
        public string AttendCard
        {
            get { return _AttendCard; }
            set
            {
                this.OnPropertyValueChange("AttendCard");
                this._AttendCard = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("State")]
        public int State
        {
            get { return _State; }
            set
            {
                this.OnPropertyValueChange("State");
                this._State = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("State2")]
        public int State2
        {
            get { return _State2; }
            set
            {
                this.OnPropertyValueChange("State2");
                this._State2 = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("LastPassTime")]
        public DateTime LastPassTime
        {
            get { return _LastPassTime; }
            set
            {
                this.OnPropertyValueChange("LastPassTime");
                this._LastPassTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("LastVisitTime")]
        public DateTime LastVisitTime
        {
            get { return _LastVisitTime; }
            set
            {
                this.OnPropertyValueChange("LastVisitTime");
                this._LastVisitTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("LastIp")]
        public string LastIp
        {
            get { return _LastIp; }
            set
            {
                this.OnPropertyValueChange("LastIp");
                this._LastIp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Disabled")]
        public bool Disabled
        {
            get { return _Disabled; }
            set
            {
                this.OnPropertyValueChange("Disabled");
                this._Disabled = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("BindIp")]
        public string BindIp
        {
            get { return _BindIp; }
            set
            {
                this.OnPropertyValueChange("BindIp");
                this._BindIp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UsingKey")]
        public bool UsingKey
        {
            get { return _UsingKey; }
            set
            {
                this.OnPropertyValueChange("UsingKey");
                this._UsingKey = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UGuid")]
        public string UGuid
        {
            get { return _UGuid; }
            set
            {
                this.OnPropertyValueChange("UGuid");
                this._UGuid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UKey")]
        public string UKey
        {
            get { return _UKey; }
            set
            {
                this.OnPropertyValueChange("UKey");
                this._UKey = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("UExt")]
        public string UExt
        {
            get { return _UExt; }
            set
            {
                this.OnPropertyValueChange("UExt");
                this._UExt = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
                _.UserId,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.UserId,
                _.UserId2,
                _.UserNo,
                _.UserName,
                _.Password,
                _.IDNumber,
                _.PrivId,
                _.Expand,
                _.PostPriv,
                _.PostDept,
                _.DeptId,
                _.CanBroadcast,
                _.Sex,
                _.Birthday,
                _.IsHideBirthday,
                _.TelNoDept,
                _.FaxNoDept,
                _.AddressHome,
                _.ZipHome,
                _.TelHome,
                _.Mobile,
                _.IsHideMobile,
                _.Bp,
                _.Email,
                _.Oicq,
                _.Icq,
                _.Msn,
                _.Skype,
                _.Photo,
                _.NickName,
                _.Avatar,
                _.MenuType,
                _.MenuHide,
                _.SmsOn,
                _.CallSound,
                _.Theme,
                _.Note,
                _.MytableLeft,
                _.MytableRight,
                _.EmailCapacity,
                _.FolderCapacity,
                _.OnlineTime,
                _.DutyType,
                _.AttendCard,
                _.State,
                _.State2,
                _.LastPassTime,
                _.LastVisitTime,
                _.LastIp,
                _.Disabled,
                _.BindIp,
                _.UsingKey,
                _.UGuid,
                _.UKey,
                _.UExt,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._UserId,
                this._UserId2,
                this._UserNo,
                this._UserName,
                this._Password,
                this._IDNumber,
                this._PrivId,
                this._Expand,
                this._PostPriv,
                this._PostDept,
                this._DeptId,
                this._CanBroadcast,
                this._Sex,
                this._Birthday,
                this._IsHideBirthday,
                this._TelNoDept,
                this._FaxNoDept,
                this._AddressHome,
                this._ZipHome,
                this._TelHome,
                this._Mobile,
                this._IsHideMobile,
                this._Bp,
                this._Email,
                this._Oicq,
                this._Icq,
                this._Msn,
                this._Skype,
                this._Photo,
                this._NickName,
                this._Avatar,
                this._MenuType,
                this._MenuHide,
                this._SmsOn,
                this._CallSound,
                this._Theme,
                this._Note,
                this._MytableLeft,
                this._MytableRight,
                this._EmailCapacity,
                this._FolderCapacity,
                this._OnlineTime,
                this._DutyType,
                this._AttendCard,
                this._State,
                this._State2,
                this._LastPassTime,
                this._LastVisitTime,
                this._LastIp,
                this._Disabled,
                this._BindIp,
                this._UsingKey,
                this._UGuid,
                this._UKey,
                this._UExt,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Users");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId = new Field("UserId", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserId2 = new Field("UserId2", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserNo = new Field("UserNo", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UserName = new Field("UserName", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Password = new Field("Password", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IDNumber = new Field("IDNumber", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PrivId = new Field("PrivId", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Expand = new Field("Expand", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PostPriv = new Field("PostPriv", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PostDept = new Field("PostDept", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DeptId = new Field("DeptId", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CanBroadcast = new Field("CanBroadcast", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Sex = new Field("Sex", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Birthday = new Field("Birthday", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsHideBirthday = new Field("IsHideBirthday", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TelNoDept = new Field("TelNoDept", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FaxNoDept = new Field("FaxNoDept", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddressHome = new Field("AddressHome", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ZipHome = new Field("ZipHome", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TelHome = new Field("TelHome", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Mobile = new Field("Mobile", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsHideMobile = new Field("IsHideMobile", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Bp = new Field("Bp", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Email = new Field("Email", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Oicq = new Field("Oicq", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Icq = new Field("Icq", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Msn = new Field("Msn", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Skype = new Field("Skype", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Photo = new Field("Photo", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NickName = new Field("NickName", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Avatar = new Field("Avatar", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MenuType = new Field("MenuType", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MenuHide = new Field("MenuHide", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field SmsOn = new Field("SmsOn", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CallSound = new Field("CallSound", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Theme = new Field("Theme", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Note = new Field("Note", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MytableLeft = new Field("MytableLeft", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MytableRight = new Field("MytableRight", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EmailCapacity = new Field("EmailCapacity", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FolderCapacity = new Field("FolderCapacity", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OnlineTime = new Field("OnlineTime", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DutyType = new Field("DutyType", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AttendCard = new Field("AttendCard", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State = new Field("State", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field State2 = new Field("State2", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LastPassTime = new Field("LastPassTime", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LastVisitTime = new Field("LastVisitTime", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LastIp = new Field("LastIp", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Disabled = new Field("Disabled", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BindIp = new Field("BindIp", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UsingKey = new Field("UsingKey", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UGuid = new Field("UGuid", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UKey = new Field("UKey", "Users", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field UExt = new Field("UExt", "Users", "");
        }
        #endregion
    }
}