//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace CodingLei_Model.TableModel
{
    /// <summary>
    /// 实体类WorkSoultion。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("WorkSoultion")]
    [Serializable]
    public partial class WorkSoultion : Entity
    {
        #region Model
        private int _Id;
        private int? _DelStatus;
        private DateTime? _AddTime;
        private string _Title;
        private string _Describe;
        private string _Solution;
        private string _PicUrl;
        private string _SoultionPicUrl;
        private string _EmployeeId;
        private int? _Type;
        private string _EmployeeName;
        private string _Phone;

        /// <summary>
        /// 
        /// </summary>
        [Field("Id")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("DelStatus")]
        public int? DelStatus
        {
            get { return _DelStatus; }
            set
            {
                this.OnPropertyValueChange("DelStatus");
                this._DelStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("AddTime")]
        public DateTime? AddTime
        {
            get { return _AddTime; }
            set
            {
                this.OnPropertyValueChange("AddTime");
                this._AddTime = value;
            }
        }
        /// <summary>
        /// 标题
        /// </summary>
        [Field("Title")]
        public string Title
        {
            get { return _Title; }
            set
            {
                this.OnPropertyValueChange("Title");
                this._Title = value;
            }
        }
        /// <summary>
        /// 描述
        /// </summary>
        [Field("Describe")]
        public string Describe
        {
            get { return _Describe; }
            set
            {
                this.OnPropertyValueChange("Describe");
                this._Describe = value;
            }
        }
        /// <summary>
        /// 解决方案
        /// </summary>
        [Field("Solution")]
        public string Solution
        {
            get { return _Solution; }
            set
            {
                this.OnPropertyValueChange("Solution");
                this._Solution = value;
            }
        }
        /// <summary>
        /// 问题图片
        /// </summary>
        [Field("PicUrl")]
        public string PicUrl
        {
            get { return _PicUrl; }
            set
            {
                this.OnPropertyValueChange("PicUrl");
                this._PicUrl = value;
            }
        }
        /// <summary>
        /// 解决方案图片
        /// </summary>
        [Field("SoultionPicUrl")]
        public string SoultionPicUrl
        {
            get { return _SoultionPicUrl; }
            set
            {
                this.OnPropertyValueChange("SoultionPicUrl");
                this._SoultionPicUrl = value;
            }
        }
        /// <summary>
        /// 员工Id
        /// </summary>
        [Field("EmployeeId")]
        public string EmployeeId
        {
            get { return _EmployeeId; }
            set
            {
                this.OnPropertyValueChange("EmployeeId");
                this._EmployeeId = value;
            }
        }
        /// <summary>
        /// 类型
        /// </summary>
        [Field("Type")]
        public int? Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("EmployeeName")]
        public string EmployeeName
        {
            get { return _EmployeeName; }
            set
            {
                this.OnPropertyValueChange("EmployeeName");
                this._EmployeeName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        [Field("Phone")]
        public string Phone
        {
            get { return _Phone; }
            set
            {
                this.OnPropertyValueChange("Phone");
                this._Phone = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.DelStatus,
                _.AddTime,
                _.Title,
                _.Describe,
                _.Solution,
                _.PicUrl,
                _.SoultionPicUrl,
                _.EmployeeId,
                _.Type,
                _.EmployeeName,
                _.Phone,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._DelStatus,
                this._AddTime,
                this._Title,
                this._Describe,
                this._Solution,
                this._PicUrl,
                this._SoultionPicUrl,
                this._EmployeeId,
                this._Type,
                this._EmployeeName,
                this._Phone,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "WorkSoultion");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "WorkSoultion", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DelStatus = new Field("DelStatus", "WorkSoultion", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime", "WorkSoultion", "");
            /// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title", "WorkSoultion", "标题");
            /// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Describe = new Field("Describe", "WorkSoultion", "描述");
            /// <summary>
			/// 解决方案
			/// </summary>
			public readonly static Field Solution = new Field("Solution", "WorkSoultion", "解决方案");
            /// <summary>
			/// 问题图片
			/// </summary>
			public readonly static Field PicUrl = new Field("PicUrl", "WorkSoultion", "问题图片");
            /// <summary>
			/// 解决方案图片
			/// </summary>
			public readonly static Field SoultionPicUrl = new Field("SoultionPicUrl", "WorkSoultion", "解决方案图片");
            /// <summary>
			/// 员工Id
			/// </summary>
			public readonly static Field EmployeeId = new Field("EmployeeId", "WorkSoultion", "员工Id");
            /// <summary>
			/// 类型
			/// </summary>
			public readonly static Field Type = new Field("Type", "WorkSoultion", "类型");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EmployeeName = new Field("EmployeeName", "WorkSoultion", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Phone = new Field("Phone", "WorkSoultion", "");
        }
        #endregion
    }
}